/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scoreBoard;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class FootballGameTest {
    private FootballTeam teamA;
    private FootballTeam teamB;
    private FootballGame game;

    @BeforeEach
    public void setup() {
        teamA = new FootballTeam("Canada");
        teamB = new FootballTeam("Spain");


    }
    @Test
    public void testGameCreateWithZeroScore() {

        game = new FootballGame(teamA, teamB);
        assertEquals(0, game.getHomeScore());
        assertEquals(0, game.getAwayScore());

    }

    @Test
    public void testGameCreateTeamName() {

        game = new FootballGame(teamA, teamB);
        assertEquals(game.getHomeTeam().getName(), "Canada");
        assertEquals(game.getAwayTeam().getName(), "Spain");

    }

}