/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ScoreBoard;

import org.junit.Test;
import static org.junit.Assert.*;

public class FootballGameTest {
    @Test public void someLibraryMethodReturnsTrue() {
        FootballGame classUnderTest = new FootballGame();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
